config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :activities
  resources :companies

   resources :activities

   root 'activities#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
has_many :users
accepts_nested_attributes_for :users
end

app/models/company.rb
class Company < ActiveRecord::Base
	validates :name, :rut, presence: true, uniqueness: true
	validates :address, :category, presence: true

	has_many :users
	accepts_nested_attributes_for :users
end
 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :company 
  belongs_to :activities      
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
   @activities = Activity.all
  # @activities = current_user.activity
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:code, :area, :team, :startdate, :week, :shift, :month, :year, :supervisor, :summaty, :category, :activity, :hours, :user_id, user_attributes: [:id, :name])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :lastname, :email, :password, :password_confirm, :remember_me, :company_id, company_attributes: [:id, :name]) }
  	devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name,  :lastname, :email, :password, :remember_me) }
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :lastname, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_action :authenticate_user!
	#Get /companies
	def index
		@companies = Company.all
	end
	#Get /companies/:id
	def show
		@company = Company.find(params[:id])
	end

	#Get /companies
	def new
		@company = Company.new
	end

	def edit
		@company = Company.find(params[:id])
	end

	#POST /companies
	def create
		@company = Company.new(companies_params)
		if @company.save
			redirect_to @company
		else
			render :new
		end
	end

	#DELETE /companies/:id
	def destroy
		@company = Company.find(params[:id])
		@company.destroy 
		redirect_to companies_path
	end

	#PUT /companies/:id
	def update
		@company = Company.find(params[:id])
		if @company.update(companies_params)
			redirect_to @company
		else
			render :edit
		end
	end

	private

	def companies_params
		params.require(:company).permit(:name, :category, :rut, :address)
		
	end

	
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/activities/_form.html.erb
<%= simple_form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :team %><br>
    <%= f.text_field :team %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br>
    <%= f.datetime_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :week %><br>
    <%= f.number_field :week %>
  </div>
  <div class="field">
    <%= f.label :shift %><br>
    <%= f.text_field :shift %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.text_field :month %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :supervisor %><br>
    <%= f.text_field :supervisor %>
  </div>
  <div class="field">
    <%= f.label :summaty %><br>
    <%= f.text_field :summaty %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :activity %><br>
    <%= f.text_field :activity %>
  </div>
  <div class="field">
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listas de actividades</h1> 
 <% if user_signed_in? %>
<p> <%= link_to "cerrar sesion", destroy_user_session_path, method: :delete %></p>
<%end%>
<h1 class="field">Bienvenido (a) <%= current_user.name %></h1>
<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Area</th>
      <th>Team</th>
      <th>Startdate</th>
      <th>Week</th>
      <th>Shift</th>
      <th>Month</th>
      <th>Year</th>
      <th>Supervisor</th>
      <th>Summaty</th>
      <th>Category</th>
      <th>Activity</th>
      <th>Hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.code %></td>
        <td><%= activity.area %></td>
        <td><%= activity.team %></td>
        <td><%= activity.startdate %></td>
        <td><%= activity.week %></td>
        <td><%= activity.shift %></td>
        <td><%= activity.month %></td>
        <td><%= activity.year %></td>
        <td><%= activity.supervisor %></td>
        <td><%= activity.summaty %></td>
        <td><%= activity.category %></td>
        <td><%= activity.activity %></td>
        <td><%= activity.hours %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @activity.code %>
</p>

<p>
  <strong>Area:</strong>
  <%= @activity.area %>
</p>

<p>
  <strong>Team:</strong>
  <%= @activity.team %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @activity.startdate %>
</p>

<p>
  <strong>Week:</strong>
  <%= @activity.week %>
</p>

<p>
  <strong>Shift:</strong>
  <%= @activity.shift %>
</p>

<p>
  <strong>Month:</strong>
  <%= @activity.month %>
</p>

<p>
  <strong>Year:</strong>
  <%= @activity.year %>
</p>

<p>
  <strong>Supervisor:</strong>
  <%= @activity.supervisor %>
</p>

<p>
  <strong>Summaty:</strong>
  <%= @activity.summaty %>
</p>

<p>
  <strong>Category:</strong>
  <%= @activity.category %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @activity.activity %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @activity.hours %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/companies/_form.html.erb

<%= form_for(@company) do |f| %>
	<% @company.errors.full_messages.each do |message| %>
		<div><%= message %></div>
	<%end%>
	<div>
		<%= f.text_field :name, placeholder: "Name of company" %>
	</div>
	<div>
		<%= f.text_field :category, placeholder: "Enter category" %>
	</div>
	<div>
		<%= f.text_field :rut, placeholder: "Rut of company" %>
	</div>
	<div>
		<%= f.text_field :address, placeholder: "Address of company" %>
	</div>
	<br>
	<div>
		<%= f.submit "Save" %>
	</div>
	
<%end%>

app/views/companies/edit.html.erb
<h1>Editar Empresas</h1>
<%= render "form" %>

app/views/companies/index.html.erb
<h1> Pagina Index Empresas </h1>
<table>
  <thead>
    <tr>
      <th>Nombre empresa </th>
      <th>Rubro </th>
      <th>Rut </th>
      <th>Dirección </th>
      	
    </tr>
  </thead>

  <tbody>
  <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, company %></td>
        <td><%= company.category %></td>
        <td><%= company.rut %></td>
        <td><%= company.address %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/new.html.erb
<h1>Agregar Empresas</h1>
<%= render "form" %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>
<div>
<%= @company.category %>
<%= @company.rut %>
<%= @company.address %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Productiva65</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>